FROM mcr.microsoft.com/aifx/acpt/stable-ubuntu2004-cu118-py310-torch220

RUN git clone https://github.com/OpenAccess-AI-Collective/axolotl
WORKDIR axolotl

RUN pip3 install packaging ninja
RUN pip3 install -e '.[flash-attn,deepspeed]'
COPY integration_utils.py /opt/conda/envs/ptca/lib/python3.10/site-packages/transformers/integrations/integration_utils.py

RUN pip3 install azureml-mlflow mlflow