FROM mcr.microsoft.com/aifx/acpt/stable-ubuntu2004-cu118-py310-torch220

RUN git clone https://github.com/OpenAccess-AI-Collective/axolotl
WORKDIR axolotl

RUN pip3 install packaging ninja
RUN pip3 install -e '.[flash-attn,deepspeed]'